# Generated by Django 4.0.2 on 2022-02-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
